import type { Metadata } from "next";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <div className="w-[420px] mx-auto h-screen min-h-screen bg-[#fff]">
          {children}
        </div>
      </body>
    </html>
  );
}
